In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("/content/linear_regression_train.csv")

In [3]:
# filling empty values with mean of given values
for i in range((df.shape[1] - 2)):
  df.iloc[:, i + 1] = df.iloc[:, i + 1].fillna(df.iloc[:, i + 1].mean())

In [11]:
# using gradient descent
X = np.zeros((df.shape[0], (df.shape[1] - 2)))
for j in range(25):
 X[:,j] = df.iloc[:,j+1]

Y = df['Target'].values

X_b = np.c_[np.ones((X.shape[0],1)), X]

theta = np.random.randn((X.shape[1] + 1), 1)

eta = 0.00001
n_iterations = 5000
m = int(X.shape[0])


for iteration in range(n_iterations):
    gradients = (1/m) * X_b.T.dot(X_b.dot(theta) - Y.reshape(48000,1))
    theta = theta - eta * gradients

In [12]:
print(theta)

[[ 5.53826940e-02]
 [ 1.42064104e+01]
 [ 6.99350278e+00]
 [ 1.22843789e+01]
 [ 1.82976340e+01]
 [-1.58037643e+00]
 [ 4.74431030e+01]
 [ 1.20076673e+01]
 [-7.63898073e+00]
 [ 1.53815121e+01]
 [ 7.09863258e+00]
 [-2.01670824e-01]
 [-4.59585555e-01]
 [ 2.38497181e+01]
 [ 5.89728341e+01]
 [ 1.63002954e+00]
 [ 2.63363360e+01]
 [ 4.18624670e-01]
 [ 1.35305792e+01]
 [ 3.07830216e+01]
 [ 4.43313919e+01]
 [ 1.95962563e+00]
 [-3.02440087e-01]
 [-2.68472652e+01]
 [ 1.20782153e+01]
 [ 1.28496903e-01]]


In [ ]:
# # using normal equation
# X = np.zeros((df.shape[0], (df.shape[1] - 2)))
# for j in range(25):
#   X[:,j] = df.iloc[:,j+1]

# Y = df['Target'].values

# X_b = np.c_[np.ones((X.shape[0],1)), X]

# theta = np.linalg.inv(X_b.T.dot(X_b)).dot(X_b.T).dot(Y)

In [ ]:
# >>> theta

array([ 7.02495240e+03,  1.35015772e+01,  1.10183522e-01,  1.20295096e+01,
        1.84741354e+01, -2.76351226e-02,  4.89191231e+01,  1.27402166e+01,
       -8.70471982e-02,  1.60389128e+01,  6.58823069e+00,  1.83481319e-02,
        8.69696865e-03,  2.47536761e+01,  5.23550134e+01, -8.62213715e-02,
        2.72681349e+01,  6.71384283e-01,  1.34718107e+01,  3.07256259e+01,
        4.59129883e+01,  2.93714200e+00,  4.22301773e-02,  2.28845016e+01,
        1.21541959e+01,  1.91413836e-02])

In [6]:
test_df = pd.read_csv("/content/linear_regression_test.csv")

for i in range((df.shape[1] - 1)):
  test_df.iloc[:, i + 1] = test_df.iloc[:, i + 1].fillna(test_df.iloc[:, i + 1].mean())

X_test = np.zeros((test_df.shape[0], (test_df.shape[1] - 1)))
for j in range((test_df.shape[1]-1)):
    X_test[:, j] = test_df.iloc[:, j+1]

X_test_b = np.c_[np.ones((test_df.shape[0], 1)), X_test]

test_predictions = X_test_b.dot(theta)

In [13]:
test_predictions

array([[ 970.14564875],
       [4569.36150249],
       [4252.22843122],
       ...,
       [5359.17643398],
       [-100.03007854],
       [ 466.9007906 ]])